spring:
  spring:
    mvc:
      throw-exception-if-no-handler-found: true

  datasource:
    url: jdbc:mysql://localhost:3306/snowmandatabase?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: snowman-admin
    password: snowman-admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: jpa-hikari-pool
      maximum-pool-size: 10
      idleTimeout: 300
      maxLifeTime: 300
      data-source-properties:
        rewriteBatchedStatements: true

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 100MB

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        default_batch_fetch_size: ${chunkSize:100}
        jdbc.batch_size: 20
        order_inserts: true
        order_updates: true
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        use_sql_comments: true

jwt:
  secret-Key: asdfasdfasdfasdrt123a1241qwetqpknapilugipk1j23k4lhj1adfkj9312kl3nasdkflj9Nvlnyasdfakljf891023jhlkasdf91nkhldf91kjlas90dfjl1k29azalikdjf912kjl3lasd9f0j1kl239asdjlkf
  access-token-expire-period: 7200      #2시간
  refresh-token-expire-period: 1209600  #2주
