spring:
  spring:
    mvc:
      throw-exception-if-no-handler-found: true

  datasource:
    url: jdbc:mysql://localhost:3306/snowmandatabase?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: snowman-admin
    password: snowman-admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: jpa-hikari-pool
      maximum-pool-size: 15
      idleTimeout: 400
      maxLifeTime: 400
      data-source-properties:
        rewriteBatchedStatements: true

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 100MB

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        jdbc.batch_size: 1000
        order_inserts: true
        order_updates: true
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        use_sql_comments: true
        jdbc:
          batch_versioned_data: true

jwt:
  secret-Key: asdfasdfasdfasdrt123a1241qwetqpknapilugipk1j23k4lhj1adfkj9312kl3nasdkflj9Nvlnyasdfakljf891023jhlkasdf91nkhldf91kjlas90dfjl1k29azalikdjf912kjl3lasd9f0j1kl239asdjlkf
  access-token-expire-period: 7200      #2시간
  refresh-token-expire-period: 1209600  #2주

weather:
  api:
    url : http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0/getVilageFcst
    secret-key: 33hVGSyTGG6f3X3ydJKyNxksJM6vVz8BUlyZ6%2FD%2BTl1SK50t6bhkhFUWQu%2Ba5A7F7zslfRHnLdZCr1ChhYn63A%3D%3D
    page-no: 1
    num-of-rows: 302
    data-type: JSON

reverse-geocoding:
  api:
    url: https://dapi.kakao.com/v2/local/geo/coord2regioncode.json
    header: KakaoAK a11cfef2b3a466c46d74ebb54494324e